# Generated by Django 2.1.3 on 2019-01-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='producer',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
