# Generated by Django 2.1.3 on 2019-01-01 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_auto_20190101_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('explanation_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='film_app.Poster'),
            preserve_default=False,
        ),
    ]
